### ISSUE TITLE
Release notes for 1.1.0

### ISSUE THREAD

**Issue by ebidel** [GoogleWebComponents/google-chart#126]
@wesalvaro Can you create some bullet points with the major changes and examples with the new loader?

**Comment by wesalvaro** [comment]
# Major Changes

- A new element `googleChartLoader` has been created. See below for details.
- Package loading is debounced to load all packages in one call.

# Bug Fixes

- `google.charts.load` is only called once
- Material chart types may be added (`md-bar` added as sample)
- Some tests were updated

# Minor API Changes

- `google-chart-render` event correctly renamed to `google-chart-ready`
- `google-chart-select` event no longer contains the selection directly
- The stopgap `googleChart.pkg` is gone. Instead, use:
  - `googleChartLoader.dataTable` to create a promise for a DataTable
  - `googleChartLoader.dataView` to create a promise for a DataView
- `googleChart.getImageURI()` is now `googleChart.imageURI`

# The &lt;google-chart-loader&gt;

## Do I need it?

You won't need it unless you:
- Make use of DataTables, DataViews, etc.
- Create charts dynamically

If that's not you, then you don't need to read any of this. The `googleChart` element itself contains a loader to make sure that the packages for the chart type you've requested are in place.

## What is it?

The `googleChartLoader` element is responsible for loading all of the visualization packages required for rendering charts. This should be done at page load so that `google.charts.load` is only called once. The element will also create promises for DataTables and DataViews as well as attach event listeners to the chart.

## How do I use it?

If you fall into the above crowd of DataView/DataTable/etc. users or you want to create charts long after the page has been loaded, here's what you need to know:

### Create

```js
var myLoader = document.createElement('google-chart-loader');
```

```html
<google-chart-loader id="myLoader"></google-chart-loader>
```

### Create a DataTable

```js
myLoader.dataTable([cols, ...rows]).then(function(dataTable) {
  // Do something with the dataTable...
  chart.data = dataTable;
});
```

### Create a DataView

```es6
myLoader.dataTable([cols, ...rows])
  .then((dataTable) => {
    this.dataTable = dataTable;
    return loader.dataView(dataTable);
  })
  .then((dataView) => {
    // Do something with the dataView...
    chart.view = dataView;
  });
```

### Preload packages for charts created dynamically after pageload

Chart packages should be loaded all-at-once on pageload. If you are creating charts of various types/packages after pageload, you should use a loader element to make sure the proper packages are loaded immediately as `google.charts.load` may only be called once at the moment.

If this is you, just place a `googleChartLoader` element with the needed details in some markup that is loaded with the page:

```html
<!-- load by package name -->
<google-chart-loader packages='["gauge", "timeline"]'></google-chart-loader>
<!-- load by chart type -->
<google-chart-loader type="table"></google-chart-loader>
```

### Other functionality

The `googleChartLoader` element also exposes two other public methods: `create` and `fireOnChartEvent`. These two functions are not ready for the prime time, so you shouldn't use them quite yet. The loader that actually loads the packages also fires a `loaded` event with it, but you probably shouldn't rely on that right now, either.

**Comment by wesalvaro** [comment]
I'm not sure how big of a deal a release is, but I had another change #127 that I wanted to get in. Working on fixing the PR right now.

**Comment by ebidel** [comment]
Awesome, thank you! I'll release after 127 is merged.

**Comment by wesalvaro** [comment]
I've created a draft release [here](https://github.com/GoogleWebComponents/google-chart/releases/tag/untagged-8a8ecf852e24bc62cea0).
