### ISSUE TITLE
All series trendline

### ISSUE THREAD

**Issue by lfelipequiros** [GoogleWebComponents/google-chart#211]
**Context:** 

Hey, I have a [combo chart](https://developers.google.com/chart/interactive/docs/gallery/combochart),  and I need a trendline that uses all series data to create it. 

Is there a way to accomplish that?

**Work on this:**

I have tried to make like an "invisible series" with all the data to make a trendline for that one and get it, but the thing is: At the moment I create more than 1 row with the same X-axis ID (like the same date) the chart collapses and start drawing lines instead of bars.

The other option i've tried is to calculate the trendline on my own and work just fine, just adding a new series with that data. But with this approach, i  cannot get the tooltip displaying the R2 on each point of the trendline.

**QUESTION:**
Is there a way to get the trendline of a combo chart that takes into account all the series data?

Should we think about a new feature of the lib? or is already a way to accomplish this?

**Comment by wesalvaro** [comment]
Hmmm... It's not currently possible to do a trendline for more than one series.
And you're right, you can't do two identical X-axis IDs.

Since you've already computed your own trend line, I think that's the way to go on a ComboChart. As for the tooltip issue, you can define you're own with the [Tooltip Role](https://developers.google.com/chart/interactive/docs/roles#tooltiprole) and perhaps the [Tooltip Options](https://developers.google.com/chart/interactive/docs/gallery/combochart#configuration-options).

How does that sound? 
As for a feature request, you'll want to request it over at the [google-visualization issue tracker](https://github.com/google/google-visualization-issues/issues) as this repository is just for the Polymer wrapper.
