### ISSUE TITLE
datetime format!

### ISSUE THREAD

**Issue by mwinters-stuff** [GoogleWebComponents/google-chart#6]
I have been trying to get data from my server (java appengine) into a line chart.
The first column is a datetime. I have previously had this working using the gwt-visulization library.

I am setting the cols/rows with the following values, 
cols = [{"label":"Timestamp", "type":"datetime"},{"label":"Jessica's Room", "type":"number"},{"label":"Main Bedroom", "type":"number"},{"label":"Lounge", "type":"number"},{"label":"Office", "type":"number"},{"label":"Outdoors", "type":"number"}]

rows = [["2014-07-03T12:00:00.000+1200", "NaN", "NaN", "NaN", "NaN", "NaN"],["2014-07-03T12:10:00.000+1200", "NaN", "NaN", "NaN", "NaN", "NaN"]]

(excuse the NAN, I am only interested in the datetime.

The error in the javascript console is
Exception caught during observer callback: Error: Type mismatch. Value 2014-07-03T12:00:00.000+1200 does not match type datetime in column index 0

I have tried many different formats, this seems to be the one most compatible with the Javascript Date object.

Any help? Thanks.

**Comment by crossi36** [comment]
Sorry for reviving this issue, but I have the same problem and your provided example doesn't work for me (maybe because it's almost a year old and something has changed in that time?). 

I copied your example, replaced `TIMESTAMP_GOES_HERE` with an actual timestamp (tried multiple ways to format the timestamp) and get the error `Type mismatch. Value [insert timestamp here] does not match type datetime in column index 0`.
