### ISSUE TITLE
Annotation chart displayRangeSelector is using only "log scale version"

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleWebComponents/google-chart#96]
For negative data, "log scale version" is not working. And normal scale is desired for a lot of data that are not financial.

**Comment by ebidel** [comment]
Please provide a jsbin that repos the issue.

**Comment by VelizarVESSELINOV** [comment]
Can you be more precise about jsbin? 

From your documentation:
```
displayRangeSelector	
Whether to show the zoom range selection area (the area at the bottom of the chart), where false means no.

The outline in the zoom selector is a log scale version of the first series in the chart, scaled to fit the height of the zoom selector.

Type: boolean
Default: true
```

I want to have displayRangeSelector true, but not with **log scale version**, but **normal scale version**.

**Comment by ebidel** [comment]
https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs

**Comment by VelizarVESSELINOV** [comment]
Thank you for the polymer contributing policy, not sure what is the link with Google Charts.
The document is talking about bug issue submission, do I need to understand that you accept only bug submissions and enhancement suggestions are ignored by default by Google chart.

**Comment by ebidel** [comment]
Sorry. It was unclear from your original comment that this was a feature request. "For negative data, "log scale version" is not working." reads like a bug.

In the future, it would be helpful if you could mention that along with enumerating the intended behavior and existing behavior (if any). I asked for a jsbin because I assumed this was a bug report based on your comment.

I'm confused on what the ask is. Is it "`displayRangeSelector: true` should support normal scale version."?

Generally, we need to adopt of the issue template used on https://github.com/Polymer/polymer/issues/new so there's less confusion in the future.

**Comment by VelizarVESSELINOV** [comment]
I think I submitted the tickets to the wrong Google Chart issue list. Apparently there is another one https://github.com/google/google-visualization-issues/issues/ with less polymer focus. If you wish close the issues I will submit them in the more general Google chart issue project.
